baseURL = 'https://kyicy.github.io/'
languageCode = 'en-us'
title = 'Raw Thoughts'
theme = "PaperMod"

googleAnalytics = "G-6ZBJPZ4FML"


[author]
name = "kyicy"
homepage = "https://github.com/kyicy"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[menu.main]]
name = "Archive"
url = "archives"
weight = 5

[[menu.main]]
name = "Search"
url = "search"
weight = 10

[[menu.main]]
name = "Tags"
url = "tag"
weight = 10

[[menu.main]]
name = "Tools"
url = "/custom_html/tools.html"


[params]
env = "production"
defaultTheme = "auto"
ShowReadingTime = true

[params.cover]
hidden = true
hiddenInList = true
hiddenInSingle = true

[params.editPost]
URL = "https://github.com/kyicy.github.io/content"
Text = "Suggest Changes"
appendFilePath = true

[outputs]
home = ["HTML", "RSS", "JSON"]
